version: "3.9"
services:
  pdal:
    build: .
    container_name: pdal
    working_dir: /pointcloud
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONBUFFERED=1
    command: python3 pipeline.py
    volumes:
      - ./pointcloud:/pointcloud
