version: "3.9"
services:
  pdal:
    build: .
    image: ubuntu:22.04
    container_name: pdal
    working_dir: /pointcloud
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONBUFFERED=1
    command: >
      sh -c "rm -rf /root/.gnupg /root/.npm /tmp/* /var/lib/lists/* /var/libs/dpkg/*-old /usr/local/lib/node_modules /var/cache/* /var/log/*"
      && apt-get -qq update \
      && apt-get -qq install --yes --no-install-recommends python3 python3-pip gdal-bin cmake pdal libpdal-plugin-e57 \
      && rm -rf /var/cache/* /var/log/* /var/lib/apt/lists/* /var/lib/dpkg/*-old
    volumes:
      - ./pointcloud:/pointcloud
